# The Site Configuration

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ''

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Additional parameters for datetime localization, optional. › https://github.com/iamkun/dayjs/tree/dev/src/locale
prefer_datetime_locale:

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Europe/London

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Herbie Bradley                          # the main title

tagline: A machine learning, computer science, and maths blog  # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  A machine learning, computer science, and maths blog
url: 'https://herbiebradley.com'

github:
  username: herbiebradley
social-github: herbiebradley # site.github comes with repo metadata using Github pages

twitter:
  username: herbiebradley
  card: summary_large_image

linkedin: herbiebradley

# Author Settings
author:
  twitter: herbiebradley
  name: Herbie Bradley
author-img: logo.jpg
logo: logo.jpg
about-author: AI for Environmental Risk PhD student at Cambridge University

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Herbie Bradley
  email: hb574@cam.ac.uk
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/herbiebradley
    - https://www.linkedin.com/in/herbiebradley
    - https://github.com/herbiebradley

google_site_verification:               # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: G-KLQ0YYE89T
  # Google Analytics pageviews report settings
  pv:
    proxy_endpoint:   # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path:       # the local PV cache data, friendly to visitors from GFW region

# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode:   # [light|dark]

# the avatar on sidebar, support local or CORS resources
avatar: avatar.jpg

mathjax: true
lato_font_load: true

# boolean type, the global switch for ToC in posts.
toc: true

comments:
  active: disqus         # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: herbiebradley    #Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo:         # <gh-username>/<repo>
    issue_term:   # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo:             # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping:          # optional, default to 'pathname'
    input_position:   # optional, default to 'bottom'
    lang:             # optional, default to the value of `site.lang`

pwa:
  enabled: true   # the option for PWA feature

# paginate: 7

# ------------ The following options are not recommended to be modified ------------------

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: "assets/pdfs/*.pdf"
    values:
      sitemap: false

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - CNAME
  - gulpfile.js
  - node_modules
  - package*.json
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - UploadToGithub.Rakefile

jekyll-archives:
  enabled: [tags]
  layouts:
    #category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    #category: /categories/:name/
