title: Flexible Jekyll Theme
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /flexible-jekyll
url: "https://shaoanlu.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: SA Lu # add your name
author-img: avatar.jpg # add your photo
about-author: Description here. # add description
twitter: home # add your Twitter handle
facebook:  # add your Facebook handle
github: shaoanlu # add your Github handle
linkedin: # add your Linkedin handle
email: shaoanlu@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
