title: Herbie Bradley
description: A Computer Science, Maths, and Machine Learning Blog
permalink: /:title
baseurl: "" # the subpath of your site, e.g. /flexible-jekyll
url: "https://herbiebradley.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Herbie Bradley
author-img: avatar.jpg
logo: avatar.jpg
about-author: Computer Science and Maths student at Keele University (2019)
twitter:
  username: herbiebradley
  card: summary
social-github: herbiebradley # site.github comes with repo metadata using Github pages
linkedin: herbiebradley
email: mail@herbiebradley.com

# Social profile for Google search results
social:
  name: Herbie Bradley
  links:
    - https://twitter.com/herbiebradley
    - https://www.linkedin.com/in/herbiebradley
    - https://github.com/herbiebradley

# Disqus
disqus-identifier: herbiebradley

# Google Analytics
google-analytics: UA-125794731-1

# Build Settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  # - jemoji

paginate: 7
paginate_path: "/page/:num"
show_drafts: false

# Front Matter Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: Herbie Bradley
      mathjax: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
