title: Herbie Bradley
description: A CS, Maths and Machine Learning Blog
permalink: /:title/
baseurl: "" # the subpath of your site, e.g. /flexible-jekyll
url: "https://herbiebradley.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Herbie Bradley # add your name
author-img: avatar.jpg # add your photo
about-author: Student # add description
twitter: herbiebradley # add your Twitter handle
facebook: # add your Facebook handle
github: herbiebradley # add your Github handle
linkedin: # add your Linkedin handle
wordpress: #
email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
google_analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

paginate: 7
paginate_path: "/page/:num"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
