title: Herbie Bradley
description: A Computer Science, Maths, and Machine Learning Blog
permalink: /:title/
baseurl: "" # the subpath of your site, e.g. /flexible-jekyll
url: "https://herbiebradley.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Herbie Bradley
author-img: avatar.jpg
about-author: Computer Science and Maths student at Keele University (2019)
twitter: herbiebradley
github: herbiebradley
linkedin: herbiebradley
email: mail@herbiebradley.com

# Disqus
disqus-identifier:

# Google Analytics
google-analytics: UA-125794731-1

# Build Settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

paginate: 7
paginate_path: "/page/:num"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
